function Bnl = B_fun(in1,in2,in3,in4)
%B_fun
%    Bnl = B_fun(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    17-Apr-2026 09:41:04

Kpc = in4(:,8);
Kpq = in4(:,2);
Kpv = in4(:,7);
Kvq = in4(:,3);
L1 = in4(:,9);
Rv = in4(:,5);
Xv = in4(:,6);
x17 = in1(17,:);
t2 = cos(x17);
t3 = sin(x17);
t4 = Rv.^2;
t5 = Xv.^2;
t6 = 1.0./L1;
t7 = Kpv.*Rv.*t2;
t8 = Kpv.*Xv.*t2;
t9 = Kpv.*Rv.*t3;
t10 = Kpv.*Xv.*t3;
t11 = t4+t5;
t12 = -t9;
t13 = t7+t10;
t14 = 1.0./sqrt(t11);
t15 = t8+t12;
Bnl = reshape([Kpc.*Kpq.*Kvq.*t6.*t13.*t14,-Kpc.*Kpq.*Kvq.*t6.*t14.*t15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Kpq.*Kvq.*t2,Kpq.*Kvq.*t3,Kpq.*Kvq.*t13.*t14,-Kpq.*Kvq.*t14.*t15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Kpc.*Kpq.*t6.*t13.*t14,-Kpc.*Kpq.*t6.*t14.*t15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Kpq.*t2,Kpq.*t3,Kpq.*t13.*t14,-Kpq.*t14.*t15],[23,3]);
end
