% function exportLight(fig, filename, varargin)
%     theme(fig,"light")
%     exportgraphics(fig, ...
%      filename,    ...
%      varargin{:}, ...
%     'Units', "pixels", ...
%     'Width', 2*600,  ...   
%     'Height', 2*400, ...
%     'Resolution', 600, ...
%     "Padding","tight")
%     theme(fig,"dark")
% end

function exportLight(fig, filename, varargin)
    theme(fig,"light")
    exportgraphics(fig, ...
     filename,    ...
     varargin{:}, ...
    'Units', 'centimeters', ...   
    'Width', 16,  ...   
    'Height', 12, ...
    'Resolution', 300) % "Padding","tight"
    theme(fig,"dark")
end


